### ISSUE TITLE
Components and Circuit

### ISSUE THREAD

**Issue by PVTPAY** [it21245/Arduino-VLC#1]
Do you have a circuit of the Arduino project and a list of components used with this code? 

Best regards
Philipp

**Comment by JohnyTripidakis** [comment]
Sorry for answering now, this is my diploma thesis and I have not looked into it since then. If you still need some info about my project you can refer to the link below
https://estia.hua.gr/browse/20893

you may check out the develop branch with a bit more readable code 
@PVTPAY
